defaults:
  - training: default
  - model: tsgraspnet
  - data: acronymvid
  - experiment: refactored_tsgrasp
  - _self_

# debug, local to tim-ubuntu
data:
  data_cfg:
    points_per_frame: 1000
    dataroot: /home/tim/Research/tsgrasp/data/acronymvid

model:
  model_cfg:
    top_confidence_quantile: 1.0
    # add_s_loss_coeff: 0.0
    # width_loss_coeff: 0.0
    pt_radius: 0.005
    grid_size: 0.005
    conv1_kernel_size: 3
    dilation: [1 1 1 1]

training:
  gpus: 1
  batch_size: 4
  save_animations: False
  make_sc_curve: False